version: "3.8"
services:

    unit:
        build: test/
        ports: 
            - "3100:80"
        volumes:
            - ./test:/var/www/html/
        container_name: unit
        # command: php database.php
        networks:
            app_unit_net:
    database:
        build: db/
        ports: 
            - "3306:3306"
        container_name: unit_db
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            app_unit_net:
    selenoid:
        container_name: selenoid
        image: aerokube/selenoid:latest-release
        volumes:
            - "/root/unit/selenoid:/etc/selenoid"
            - "/root/unit/video:/opt/selenoid/video"
            - "/root/unit/logs:/opt/selenoid/logs"
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
      # путь к видео на хосте
            - OVERRIDE_VIDEO_OUTPUT_DIR=/root/unit/video
        command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "unit_app_unit_net"]
        ports:
            - "4444:4444"
        networks:
            app_unit_net:
networks:
    app_unit_net:
        ipam:
            driver: default
            config:
                - subnet: "172.16.222.0/24"
                

        
            
